<?php
//
///**
// * Returns the id fo
// * Theme a text field as a jeditable textfield.
// *
// * @ingroup themeable
// */
//function theme_jeditable_formatter_jeditable($variables) {
//  $element     = $variables['element'];
//  $field       = $variables['field'];
//  $entity      = $variables['entity'];
//  $entity_type = $variables['entity_type'];
//  $widget_type = $variables['widget_type'];
//
//  switch ($entity_type) {
//    case 'node':
//      // Check user's access to editing this node.
//      if (!node_access('update', $entity)) {
//        return $element['value'];
//      }
//
//      $id = $entity->nid;
//      break;
//
//    case 'user':
//      // Check user's access to editing this user.
//      if (!user_edit_access($entity)) {
//        return $element['value'];
//      }
//      $id = $entity->uid;
//      break;
//  }
//  if(strpos($field['field_name'],'field_')===0) $entity_type='field';
//
//  return '<span id="' . $entity_type . '-' . $id . '-' . $field['field_name'] . '-' . $widget_type . '-' . $variables['delta'] . '" class="jeditable jeditable-textfield">' . $element['value'] . '</span>';
//}